// Global
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Create coupon
export const CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST";
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL";
export const CREATE_COUPON_RESET = "CREATE_COUPON_RESET";

// Get all coupons
export const ALL_COUPON_REQUEST = "ALL_COUPON_REQUEST";
export const ALL_COUPON_SUCCESS = "ALL_COUPON_SUCCESS";
export const ALL_COUPON_FAIL = "ALL_COUPON_FAIL";
export const ALL_COUPON_RESET = "ALL_COUPON_RESET";

// Coupon details
export const COUPON_DETAILS_REQUEST = "COUPON_DETAILS_REQUEST";
export const COUPON_DETAILS_SUCCESS = "COUPON_DETAILS_SUCCESS";
export const COUPON_DETAILS_FAIL = "COUPON_DETAILS_FAIL";

// Update coupon
export const UPDATE_COUPON_REQUEST = "UPDATE_COUPON_REQUEST";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_FAIL = "UPDATE_COUPON_FAIL";
export const UPDATE_COUPON_RESET = "UPDATE_COUPON_RESET";

// Delete coupon
export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";
export const DELETE_COUPON_RESET = "DELETE_COUPON_RESET";
